unames = {1: 'x', 2: 'y'}
parnames = {1: 'a', 2 : 'w'}
NDIM=   2, IPS =   1, IRS =   0, ILP =   1
ICP =  ['a','w']
NTST=  100, NCOL=   7, IAD =   3, ISP =   1, ISW = 1, IPLT= 0, NBC= 0, NINT= 0
NMX=  1000, NPR=  500, MXBF=  -1, IID =   2, ITMX= 8, ITNW= 7, NWTN= 3, JAC= 1
EPSL= 1e-07, EPSU = 1e-07, EPSS = 1e-05
DS  =   0.001, DSMIN=  0.00001, DSMAX=  0.01, IADS=   1
NPAR = 2, THL =  {}, THU =  {}
UZR =  { }
